### PR TITLE
Suppressed the performance warning for writing the hdf5 file

### PR DESCRIPTION
**Pull request by frqqyy**

### CODE REVIEW

**Comment by emanuel-schmid** [comment]
@frqqyy : ideally, the changes would be small enough so the diff can be shown. Since you provide no further description of the PR - could you provide some details of the essential changes?

**Comment by frqqyy** [comment]
> @frqqyy : ideally, the changes would be small enough so the diff can be shown. Since you provide no further description of the PR - could you provide some details of the essential changes?

https://github.com/CLIMADA-project/climada_python/issues/410
The change aims to solve this issue. 
And here are the codes that were added:
image

**Comment by frqqyy** [comment]
> Since there is nothing that can be done about it - wouldn't it be more appropriate to suppress it where it's raised?
> 
> Something along these lines in the exposures.base module:
> 
> ```python
> import warnings
> with warnings.catch_warnings():
>     warnings.simplefilter('ignore')
>     # code that produces a warning
> ```
> 
> (from https://stackoverflow.com/questions/54768539/suppress-a-python-warning)

Thank you, I updated the tutorial again!

**Comment by peanutfun** [comment]
@emanuel-schmid suggested that we suppress the warning in the module where `Exposures.write_hdf5` is defined, not just in the tutorial. The proposed change avoids the warning in the tutorial, but it then will appear again if `write_hdf5` is called in another script. I'm closing this PR in favor of the fix suggested in #410.

**Pull request closed without merging**
