### PR TITLE
euler user guide update

### PR DESCRIPTION
**Pull request by emanuel-schmid**
Changes proposed in this PR:
- update the Euler user guide to the newest version (the only version that runs with current develop branch) 

This PR fixes #

### PR Author Checklist

- [x] Read the [Contribution Guide][contrib]
- [x] Correct target branch selected (if unsure, select `develop`)
- [x] Descriptive pull request title added
- [x] Source branch up-to-date with target branch
- [x] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#2.--Commenting-&-Documenting) updated
- [ ] [Tests][testing] updated
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]
- [ ] [Changelog](https://github.com/CLIMADA-project/climada_python/blob/main/CHANGELOG.md) updated

### PR Reviewer Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] [CLIMADA Reviewer Checklist](https://climada-python.readthedocs.io/en/latest/guide/Guide_Reviewer_Checklist.html) passed
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]

[contrib]: https://github.com/CLIMADA-project/climada_python/blob/main/CONTRIBUTING.md
[testing]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html
[linter]: https://climada-python.readthedocs.io/en/stable/guide/Guide_Continuous_Integration_and_Testing.html#3.C.--Static-Code-Analysis

### CODE REVIEW

**Comment by chahank** [comment]
Looks clear to me. @manniepmkam Did this solve your issues?

**Comment by manniepmkam** [comment]
Yes, it works fine for me now. And this version only works with the develop branch but not the main branch. Shall we also indicate that in the guide?

**Comment by chahank** [comment]
Thanks for the feedback. There is no need to add a message about the develop branch I think. This will be merged into the develop branch only, so I think it will be clear.

**Comment by emanuel-schmid** [comment]
Thanks for the review!

**Pull request merged**
