### PR TITLE
update euler guide

### PR DESCRIPTION
**Pull request by emanuel-schmid**
Changes proposed in this PR:

- Update Euler Guide for python 3.10 and jupyter.euler.hpc.ethz.ch

This PR fixes #

### PR Author Checklist

- [ ] Read the [Contribution Guide][contrib]
- [x] Correct target branch selected (if unsure, select `develop`)
- [x] Descriptive pull request title added
- [x] Source branch up-to-date with target branch
- [x] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#2.--Commenting-&-Documenting) updated
- [ ] [Tests][testing] updated
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]
- [ ] [Changelog](https://github.com/CLIMADA-project/climada_python/blob/main/CHANGELOG.md) updated

### PR Reviewer Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] [CLIMADA Reviewer Checklist](https://climada-python.readthedocs.io/en/latest/guide/Guide_Reviewer_Checklist.html) passed
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]

[contrib]: https://github.com/CLIMADA-project/climada_python/blob/main/CONTRIBUTING.md
[testing]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html
[linter]: https://climada-python.readthedocs.io/en/stable/guide/Guide_Continuous_Integration_and_Testing.html#3.C.--Static-Code-Analysis

### CODE REVIEW

**Comment by emanuel-schmid** [comment]
the preinstalled modules on the cluster still need some tweaking

**Comment by emanuel-schmid** [comment]
> the preinstalled modules on the cluster still need some tweaking

✔️ done

**Comment by chahank** [comment]
Ready to merge?

**Comment by manniepmkam** [comment]
> Ready to merge? @manniepmkam : did the instructions work for you?

Instruction-wise yes. I haven't had time to update the CLIMADA version to the new python version and give it a try. SHall we find a volunteer or ask if anyone has run the new CLIMADA on euler recently?

**Comment by chahank** [comment]
Good! We may ask whether someone taht has tried it now.

**Pull request merged**
