### PR TITLE
Add change hazard centroids from meta

### PR DESCRIPTION
**Pull request by chahank**
This small fix allows the hazard change centroids to use the meta from the centroids.

### CODE REVIEW

**Comment by emanuel-schmid** [comment]
Naive remarks:
- This introduces another occurrence of the `meta` attribute. Is that not problematic?
- There is no unit test - or is this about improving performance?

**Comment by chahank** [comment]
> This introduces another occurrence of the meta attribute. Is that not problematic?
Indeed. But I would say this removes an inconsistency rather than adding one. The way to deal with meta needs an overhaul.
> There is no unit test, right - or is this about improving performance?
This is about being more consistent and much faster indeed. Basically, if you want to project say a Hazard computed for one country onto a grid of the whole world, the current implementation requires to make a dense matrix of all coordinates. This can quickly grow to 100GB or more of required memory. With this fix, one can use the meta an then one only needs the coordinates of the country points which is manageable memory-wise.

**Comment by chahank** [comment]
Unit test added.

**Comment by Evelyn-M** [comment]
Indeed, looks sensible!

**Comment by chahank** [comment]
@emanuel-schmid : any objections?

**Comment by emanuel-schmid** [comment]
Actually yes. Or at least I wished for some convincing about the drop_duplicates part which - at first sight - seems contradictory to the "do one thing at a time" dogma. 🧐

**Comment by emanuel-schmid** [comment]
I've moved the drop_duplicates part to a separate PR, #359

**Comment by emanuel-schmid** [comment]
Judging from the unit-test, the arbitrary removal of concurring centroids seems to be a hazardous feature with the potential of distorting the data.

Shouldn't the fraction and intensity values be aggregated in a more sensible way if we were to allow such a of pooling of centroids?

**Pull request merged**
