### PR TITLE
Replace 3 old demo files by smaller ones

### PR DESCRIPTION
**Pull request by tovogt**
As discussed in #56, the files `data/demo/tc_fl_1975_2011.h5`, `data/demo/atl_prob.mat` and `data/demo/WS_ERA40.mat` are exceedingly large. This PR replaces the files by smaller ones and makes sure that all occurrences in tutorials and tests are running fine with the smaller versions of the files.

All unit and integration tests are running fine on my machine.

### CODE REVIEW

**Comment by davidnbresch** [comment]
arl_prob.mat should be (drastically) shrunk if used for testing at all, quite old - hence better removed. Better use something you use to test IBTrACS (and via API), if I might suggest.

Prof. Dr. David N. Bresch 
Professor for Weather and Climate Risks
Institute for Environmental Decisions
ETH Zurich/MeteoSwiss
dbresch@ethz.ch <mailto:dbresch@ethz.ch>, dbresch@meteoswiss.ch <mailto:dbresch@meteoswiss.ch>
office: +41 44 632 77 87
mobile: +41 79 770 15 92
skype: davidnbresch
zoom: https://ethz.zoom.us/my/ <https://ethz.zoom.us/my/dbresch>dbresch <https://ethz.zoom.us/my/dbresch>
https://www.usys.ethz.ch/en/people/profile.david-bresch.html
http://www.wcr.ethz.ch <http://www.wcr.ethz.ch/>

**Comment by tovogt** [comment]
Thanks for the clarification! The file `atl_prob.mat` is used to test CLIMADA's util functions for reading HDF5 files. That's why I didn't remove it completely. After this PR, it's replaced by a sufficiently small file. That should be fine for now.

**Comment by chahank** [comment]
@tovogt Could you maybe assign someone that has not done much review so far to this? I think even though it is minor, it would be good if someone checks that nothing went missing right?

@davidnbresch I think you responded via email, and thus your signature is included. I am not sure whether this was intended or not.

**Comment by tovogt** [comment]
@mmyrte Jan, are you available for review? :)

**Comment by emanuel-schmid** [comment]
Sorry for short cutting the protocol but I'll accept this one. I kind of need it for my own pull request about the rasterio upgrade which I want to submit shortly.

**Comment by emanuel-schmid** [comment]
@simonameiler of course you are welcome to still have a look at the changes and comment on them. Any required changes will be amended.

**Pull request merged**
