### PR TITLE
Upgrade to Python 3.9

### LINKED ISSUE #596: Upgrade to Python 3.9+
Is there a plan to switch to newer versions of Python? The conda environment files specifically require [Python 3.8](https://github.com/CLIMADA-project/climada_python/blob/develop/requirements/env_climada.yml#L27), which is 3 years old and has now been superseded by 3 major releases.

What would be required to switch to a newer version? I would be willing to help with that, but I'm not sure which steps to take.

### PR DESCRIPTION
**Pull request by peanutfun**
Changes proposed in this PR:
- Switch requirements to Python 3.9
- Update doc environment

This PR fixes #596 

TODO:
- [ ] Update Jenkins test environment with new requirements

### PR Author Checklist

- [x] Read the [Contribution Guide][contrib]
- [x] Correct target branch selected (if unsure, select `develop`)
- [x] Source branch up-to-date with target branch
- [ ] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#2.--Commenting-&-Documenting) updated
- [ ] [Tests][testing] updated
- [x] [Tests][testing] passing
- [x] No new [linter issues][linter]

### PR Reviewer Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] [CLIMADA Reviewer Checklist](https://climada-python.readthedocs.io/en/latest/guide/Guide_Reviewer_Checklist.html) passed
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]

[contrib]: https://github.com/CLIMADA-project/climada_python/blob/main/CONTRIBUTING.md
[testing]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html
[linter]: https://climada-python.readthedocs.io/en/stable/guide/Guide_Continuous_Integration_and_Testing.html#3.C.--Static-Code-Analysis

### CODE REVIEW

**Comment by peanutfun** [comment]
@emanuel-schmid I guess changes to the requirements here will not automatically update the environment used by Jenkins for the tests. How is that one updated?

**Comment by emanuel-schmid** [comment]
Right. The environment is built when the [climada_install_env](https://ied-wcr-jenkins.ethz.ch/job/climada_install_env/) test is run at 1:30AM. And that is running on the develop branch exclusively.

So, basically, there is no automated test for environment updates. 😱

I usually start the climada_install_env test manually right after merging a PR with an environment update instead of waiting for the outcome in the morning. This also triggers a ci_night test btw.

**Comment by emanuel-schmid** [comment]
I'll give it a try on my Windows 10. 😬

**Comment by emanuel-schmid** [comment]
Looks like it won't be entirely smooth: the environment installed alright, but updating it or installing another module seems prohibited by "SSL module is not available".

Checking the options ...

**Comment by peanutfun** [comment]
This might be an issue with the conda installation on Win 10? See https://github.com/conda/conda/issues/8273

**Comment by emanuel-schmid** [comment]
(confirmed: that was a conda issue, independent from python-3.9, or climada, let alone this PR)

The new environment works totally fine for Windows10 👍

**Comment by peanutfun** [comment]
If you want to check out CLIMADA with the new Python version, follow these instructions:

1. Check out this branch:

   ```bash
   git fetch origin
   git checkout feature/python3.9
   ```
2. Create a *new* conda environment from the environment specs

   ```bash
   conda env create -n climada_env_3.9 -f requirements/env_climada.yml
    ```
3. The new environment is then called `climada_env_3.9` but within this environment, everything should work as usual:

   ```bash
   conda activate climada_env_3.9
   python my_climada_script.py
   ```
4. Your old environment `climada_env` should not be affected by this.

**Comment by mathause** [comment]
Can I ask how your pinned python version must be understood? Does it mean that you can only? should only? install climada on a specific version? Or does that mean it's only tested on a certain version? Are there reasons why it would not work on other versions? And if it is a hard pin should you consider adding this to your setup.py (`python_requires`) and to the meta.yaml on the conda feedstock?

**Comment by emanuel-schmid** [comment]
The python version is part of the conda environment that is specified in `requirements/env_climada.yaml`.
This environment is

-  our suggested way to [install climada](https://climada-python.readthedocs.io/en/latest/tutorial/climada_installation_step_by_step.html).
- the environment that Jenkins uses for automated tests
- the base of the environment that readthedocs uses for building the documentation

That's all. Hence it's not a hard pin and adding to the setup.py couldn't be justified.

**Comment by mathause** [comment]
Thanks! I am asking because of the intro course @aleeciu will teach this semester (and I am also part of). But I think we are all set.

**Pull request merged**
