### PR TITLE
Change test data impf.id to test non-default params

### PR DESCRIPTION
**Pull request by chahank**
Changes proposed in this PR:
This PR does NOT provide a bugfix after all, as this was fixed by chance in PR #666 . However, the tests do not test for this case, and thus it was added to the tests. It is very minimalistic and could be made even more consistent. But at least it provides a minimal improvement.

Basically, the impact function id is by default set to 1 under the hood in CLIMADA if none is specified. Currently, the tests only work with impact function id 1. Thus, the use case when multiple impact functions with different ids are used is not tested. The default exposures for polygons was now set to use impact functions with id = 2.

### PR Author Checklist

- [x] Read the [Contribution Guide][contrib]
- [x] Correct target branch selected (if unsure, select `develop`)
- [x] Descriptive pull request title added
- [x] Source branch up-to-date with target branch
- [x] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#2.--Commenting-&-Documenting) updated
- [x] [Tests][testing] updated
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]
- [x] [Changelog](https://github.com/CLIMADA-project/climada_python/blob/main/CHANGELOG.md) updated

### PR Reviewer Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] [CLIMADA Reviewer Checklist](https://climada-python.readthedocs.io/en/latest/guide/Guide_Reviewer_Checklist.html) passed
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]

[contrib]: https://github.com/CLIMADA-project/climada_python/blob/main/CONTRIBUTING.md
[testing]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html
[linter]: https://climada-python.readthedocs.io/en/stable/guide/Guide_Continuous_Integration_and_Testing.html#3.C.--Static-Code-Analysis

### CODE REVIEW

**Comment by Evelyn-M** [comment]
I'm not sure how the tests really checks for this case now. The two impact functions in the currently tested impact function set are functionally the same (the welker ones), and i cannot see how it is really ensured that not the imp func with ID 1 is taken (as the impact values would be the same)

**Comment by Evelyn-M** [comment]
aka, would it make sense to explicitly check that the interpolated exp_poly still has imp func id 2? and perhaps with a different impact function altogether?

**Comment by chahank** [comment]
> aka, would it make sense to explicitly check that the interpolated exp_poly still has imp func id 2? and perhaps with a different impact function altogether?

This is exactly what is done in all the tests: 

```
def check_unchanged_geom_gdf(self, gdf_geom, gdf_pnt):
    """Test properties that should not change"""
    for n in gdf_pnt.index.levels[1]:
        sub_gdf_pnt = gdf_pnt.xs(n, level=1)
        rows_sel = sub_gdf_pnt.index.to_numpy()
        sub_gdf = gdf_geom.loc[rows_sel]
        self.assertTrue(np.alltrue(sub_gdf.geometry.geom_equals(sub_gdf_pnt.geometry_orig)))
    for col in gdf_pnt.columns:
        if col not in COL_CHANGING:
            np.testing.assert_allclose(gdf_pnt[col].unique(), gdf_geom[col].unique())
```

**Comment by chahank** [comment]
> I'm not sure how the tests really checks for this case now. The two impact functions in the currently tested impact function set are functionally the same (the welker ones), and i cannot see how it is really ensured that not the imp func with ID 1 is taken (as the impact values would be the same)

That is correct.

**Comment by Evelyn-M** [comment]
> > aka, would it make sense to explicitly check that the interpolated exp_poly still has imp func id 2? and perhaps with a different impact function altogether?
> 
> This is exactly what is done in all the tests:
> 
> ```
> def check_unchanged_geom_gdf(self, gdf_geom, gdf_pnt):
>     """Test properties that should not change"""
>     for n in gdf_pnt.index.levels[1]:
>         sub_gdf_pnt = gdf_pnt.xs(n, level=1)
>         rows_sel = sub_gdf_pnt.index.to_numpy()
>         sub_gdf = gdf_geom.loc[rows_sel]
>         self.assertTrue(np.alltrue(sub_gdf.geometry.geom_equals(sub_gdf_pnt.geometry_orig)))
>     for col in gdf_pnt.columns:
>         if col not in COL_CHANGING:
>             np.testing.assert_allclose(gdf_pnt[col].unique(), gdf_geom[col].unique())
> ```

ah yeah ok, that was a bit cryptic to spot.
looks good, then.

**Pull request merged**
