### PR TITLE
adapt categorical plotting function to new matplotlib version

### PR DESCRIPTION
**Pull request by emanuel-schmid**
cit. @blassr "Colorbar was continuous with the new Matplotlib 3.5 version. This is fixed and categorical again with this fix."

### CODE REVIEW

**Comment by emanuel-schmid** [comment]
@blassr : can you give an example of a colorbar that's continuous without this fix?

**Comment by blassr** [comment]
'wistia' or 'viridis'

**Review by blassr — APPROVED** [review]

**Comment by chahank** [comment]
Quick question: does it also work with Matplotlib < 3.5?

**Comment by emanuel-schmid** [comment]
> Quick question: does it also work with Matplotlib < 3.5?

Very good question! Yes it works, at least for matplotlib 3.2.
(But, completely unrelated to this PR, it ain't pretty.)

**Comment by chahank** [comment]
What is not pretty :D ?

**Comment by chahank** [comment]
I think you probably have run the method in a way that it is not intended to be used as (and probably should not be used as). You should not have more than a few categories in general.

**Comment by emanuel-schmid** [comment]
> I think you probably have run the method in a way that it is not intended to be used as (and probably should not be used as). You should not have more than a few categories in general.

Nah, it's just the font size which is way over the top. ;)

**Pull request merged**
