### PR TITLE
Feature/rename unc

### PR DESCRIPTION
**Pull request by chahank**
This branch renames the 'uncertainty_quantification' module to 'unsequa'.

### CODE REVIEW

**Comment by ChrisFairless** [comment]
I thought we voted on this renaming! Was all our democratic process a SHAM?

**Comment by ChrisFairless** [comment]
On a more serious note, reading through the diff I feel the renaming has made every script just a little bit harder to read

**Review by emanuel-schmid — APPROVED** [review]

**Comment by chahank** [comment]
> I thought we voted on this renaming! Was all our democratic process a SHAM? 
The final decision was taking by the core team around the module.

**Comment by chahank** [comment]
>On a more serious note, reading through the diff I feel the renaming has made every script just a little bit harder to read

Could you explain in what way? The only thing that changed are the imports.

**Comment by ChrisFairless** [comment]
Here I just meant that new users are going to have to look up what `import unsequa` does, whereas e.g. `import uncertainty_sensitivity` is kind of self-documenting.

However! Following a Slack chat I know more about the choice and I don't have a problem with merging!! :)

**Pull request merged**
