### PR TITLE
Docs: fix many sphinx warnings

### PR DESCRIPTION
**Pull request by tovogt**
Changes proposed in this PR:
- This only affects the docs, not any of the code or functionality.
- It only affects minor parts of the docs formatting.
- Mostly, it's about getting rid of warning messages by Sphinx when calling `make clean html`.

### PR Author Checklist

- [x] Read the [Contribution Guide][contrib]
- [x] Correct target branch selected (if unsure, select `develop`)
- [x] Source branch up-to-date with target branch
- [x] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#2.--Commenting-&-Documenting) updated
- [x] [Tests][testing] updated
- [x] [Tests][testing] passing
- [x] No new [linter issues][linter]

### PR Reviewer Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] [CLIMADA Reviewer Checklist](https://climada-python.readthedocs.io/en/latest/guide/Guide_Reviewer_Checklist.html) passed
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]

[contrib]: https://github.com/CLIMADA-project/climada_python/blob/main/CONTRIBUTING.md
[testing]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html
[linter]: https://climada-python.readthedocs.io/en/stable/guide/Guide_Continuous_Integration_and_Testing.html#3.C.--Static-Code-Analysis

### CODE REVIEW

**Comment by emanuel-schmid** [comment]
🤩 awesome!

**Comment by tovogt** [comment]
This has conflicts with #620, let me see....

**Comment by emanuel-schmid** [comment]
already solved

**Comment by tovogt** [comment]
Great, thanks!

**Pull request merged**
