### PR TITLE
installation guide, several updates:

### PR DESCRIPTION
**Pull request by emanuel-schmid**
- mention pypi installation,
- promote canonical spyder installation
- rearrange (separate core from climate more)

### CODE REVIEW

**Comment by emanuel-schmid** [comment]
@reviewers: if you have time, please have a look. Otherwise I'll just merge it and we improve as questions arise...

**Comment by chahank** [comment]
Cool, thanks! Here a few remarks.

**Comment by chahank** [comment]
I do not understand what is meat by 

> Published releases of CLIMADA (not CLIMADA-petals) can also be installed from the PyPi repository https://pypi.org/project/climada/. In this case, cloning the complete climada_python repository is not even necessary, it is sufficient to download the climada_petals/requirements/env_climada.yml file for setting up the environment.

**Comment by chahank** [comment]
I would probably remove 

> Alternatively one can create a separate Conda environment for CLIMADA-petals.

I think people that understand this sentence do not need it, the other would be confused.

**Comment by chahank** [comment]
I think this is a bit cryptic:

> Try to include the paths to climada_python and climada_petals into the environment climada_env using pip install -e as suggested above.

**Comment by chahank** [comment]
For the `How to change the log level` section, one could add a remark to the CLIMADA context manager in the utils (`from climada.util import log_level`)

**Comment by chahank** [comment]
Finally, I would add a brief explanation on top of the notebook about the differences between CLIMADA core and CLIMADA petals.

**Comment by emanuel-schmid** [comment]
> 

I've made a new paragraph for the pip installation.

**Comment by emanuel-schmid** [comment]
> 

:+1: Now the answer is: activate the climada environment - or go back to 'start'

**Comment by emanuel-schmid** [comment]
> Finally, I would add a brief explanation on top of the notebook about the differences between CLIMADA core and CLIMADA petals.

I'd rather not, That is already in the README.md of CLIMADA, repeating it here may cause sync problems.

**Pull request merged**
