### PR TITLE
Fix assign_centroids for raster hazards

### PR DESCRIPTION
**Pull request by tovogt**
As noted in #129, the centroids assignment in `Exposure.assign_centroids` is flawed for raster hazards in three ways:

1. Exposure points that lie outside of the hazard raster in longitudinal, but not in latitudinal directions, are assigned to completely wrong hazard raster points. In other words, exposure points to the (longitudinal) left or right of the hazard raster are affected.
2. The hazard raster is assumed to be nodal instead of cell-centered.
3. The assignment is not by nearest-neighbor, but by next-neighbor-to-the-left (floor instead of round).

This PR is a hot fix to make sure that the current behavior is consistent. A broader discussion of the `assign_centroids` function should remain unaffected by this. We can still change the general behavior later on.

I commited the regression tests before the fix, so you can follow the problem in the test results: https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/feature%252Ffix_assign_centroids/

### CODE REVIEW

**Comment by chahank** [comment]
Thanks, it seems to fix the issue. I however have one doubt about the following case:

(0,0)       (1,0)

(1,0)        (1,1)

Then, `xmin = 0.5, ymin=0.5`. Now, the point (0.6,0.6) should be associated with (1,1) as this is the closest point. However, `x_i = round((0.6-0.5)/1) = 0` and `y_i = round((0.6-0.5)/1) = 0`.

In the test setting, this would for instance mean the the point `(-19, 6.7)` should associated with `20`.

**Comment by ingajsa** [comment]
> Thanks, it seems to fix the issue. I however have one doubt about the following case:
> 
> (0,0) (1,0)
> 
> (1,0) (1,1)
> 
> Then, `xmin = 0.5, ymin=0.5`. Now, the point (0.6,0.6) should be associated with (1,1) as this is the closest point. However, `x_i = round((0.6-0.5)/1) = 0` and `y_i = round((0.6-0.5)/1) = 0`.
> 
> In the test setting, this would for instance mean the the point `(-19, 6.7)` should associated with `20`.

Why would xmin then be 0.5 in this case and not 0?

**Comment by chahank** [comment]
Because of `xmin, ymin = xmin + 0.5 * xres, ymin + 0.5 * yres`

**Comment by tovogt** [comment]
Maybe there is a misunderstanding about cell-centered vs. nodal grids here. In CLIMADA, always follow the GDAL-convention to have cell-centered grids, see, e.g. this example:
https://github.com/CLIMADA-project/climada_python/blob/7b132f9a58cfb48c5d38d09b0d1e3c8d3c0ddc84/climada/entity/exposures/base.py#L265-L269

**Comment by ingajsa** [comment]
> Because of `xmin, ymin = xmin + 0.5 * xres, ymin + 0.5 * yres`

Ah, sorry I considered the xmin, ymin coming out of the centroids.meta

**Pull request merged**
