### PR TITLE
Bugfix/get geometries extent antimeridian

### PR DESCRIPTION
**Pull request by bguillod**
Changes proposed in this PR:
- Ensure `climada.util.coordinates.get_land_geometry` deals correctly with extent. Previously, if an extent going beyond [-180, +180] range in longitude the geometry would be cut (e.g. passing `extent=(160, 200, -50,50)` would actually return the land geometry only for the extent `(160, 180, -50, 50)`.
- Apply the same correction to `get_country_geometry`.
- Removes the redundancy between these two functions by using the latter in the former.
- Adjust function `coord_on_land` to ensure longitude coordinates are also properly dealt with.

This PR fixes issue #495.

A first test has been implemented but this can be completed.

### Pull Request Checklist

- [x] Correct target branch selected (if unsure, select `develop`)
- [x] Source branch up-to-date with target branch
- [x] Docs updated
- [x] Tests updated
- [x] Tests passing
- [x] No new linter issues

### CODE REVIEW

**Comment by bguillod** [comment]
Working on fixing the failed checks...

**Comment by bguillod** [comment]
Ok so one last test is still failing: `test_get_land_geometry_country_pass`.

It looks as if the PR slightly changed the extent of some countries used in this test. I think this might be due to the fact that the filtering of the shapes in natural earth has been slightly adjusted within this PR.

Does anybody know who wrote these tests?

In my opinion we can update the expected value of these tests, so they pass. However I need someone else's opinion to confirm as I don't want to oversee something that also could be an issue.

**Comment by tovogt** [comment]
From my side this is ready to be merged. I just added some code clean-up for the linter, but the rest is fine.

> Ok so one last test is still failing: `test_get_land_geometry_country_pass`.
> 
> It looks as if the PR slightly changed the extent of some countries used in this test. I think this might be due to the fact that the filtering of the shapes in natural earth has been slightly adjusted within this PR.
> 
> Does anybody know who wrote these tests?
> 
> In my opinion we can update the expected value of these tests, so they pass. However I need someone else's opinion to confirm as I don't want to oversee something that also could be an issue.

The tests were broken from the start because they passed the keyword arguments as positional arguments and the result was that the `110` (which was obviously supposed to be the resolution) was actually assigned to the `extent` keyword argument, so that the actual resolution used was `10` (the default value of that keyword argument). I fixed this by explicitly selecting `10` as the resolution.

**Comment by emanuel-schmid** [comment]
🙌

**Comment by bguillod** [comment]
Thanks a lot @tovogt and @emanuel-schmid for reviewing and merging!

**Pull request merged**
