### PR TITLE
 add select by name + PEP style corrections

### PR DESCRIPTION
**Pull request by aleeciu**
The hazard base class has a method .select, which allows selecting by date, origin, reg_id (and combination of these).

To these, I added selecting by track name, which I find very handy.

Also applied few PEP-reated issues which emerged from static code analysis

### CODE REVIEW

**Comment by sameberenz** [comment]
it seems like your pull request entails many commits to develop from others that are not necessarily yet supposed to go to master (?)

**Comment by aleeciu** [comment]
Hi Samuel
I am not sure about that, I only added a very tiny functionality. I also just realized it's been committed to master, whereas I wanted to committ to develop.

shall I undo and recomitt or you can manage to do that when handling the committ?

**Comment by sameberenz** [comment]
Hi Alessio
I am not experiences in managing these kind of pull requests. I propose that you undo and solve the issue with the help of Emanuel or Chahan if you run into any problems.

**Comment by aleeciu** [comment]
Hey Samuel
I just undo and committ to develop..

**Pull request closed without merging**
