### PR TITLE
Overhaul documentation and use Book theme

### LINKED ISSUE #592: Switch to more pleasing HTML theme for CLIMADA docs
The HTML theme describes the appearence (and only the appearance) of the docs built by the Sphinx package. We currently use the almost default `sphinxdoc` theme, which I find a bit unappealing.

The theme used to display the docs can easily be changed by installing the respective theme package via pip,
```
pip install <theme-pkg>
```
and then adding the theme in the `doc/conf.py`
```python
# conf.py
html_theme = "<theme-name>"
```

Examples of commonly used themes can be found on https://sphinx-themes.org/.
* [Furo](https://sphinx-themes.org/sample-sites/furo/),
* [Book](https://sphinx-themes.org/sample-sites/sphinx-book-theme/), and 
* [Read the Docs](https://sphinx-themes.org/sample-sites/sphinx-rtd-theme/)

are amongst the most common today and I find each of them much nicer than [our current theme](https://climada-python.readthedocs.io/en/stable/index.html).

### PR DESCRIPTION
**Pull request by peanutfun**
Changes proposed in this PR:
- Switch to Book theme
- Add requirement specifications for building the documentation locally
- Add `doc/README.md` with instructions on how to build the documentation
- Add `doc/create_env_doc.dockerfile` for building the documentation environment from scratch
- Overhaul documentation with
   - New sub-structure for tutorials
   - Logos and favicon
   - Addition of missing tutorials and guides
   - Inclusion of Markdown documents from repository
   - Explanation on how to add `requirements/env_developer.yml`  to the `climada_env`

This PR resolves #592 #599 #603

### PR Author Checklist

- [x] Read the [Contribution Guide][contrib]
- [x] Correct target branch selected (if unsure, select `develop`)
- [x] Source branch up-to-date with target branch
- [x] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#2.--Commenting-&-Documenting) updated
- ~~[ ] [Tests][testing] updated~~
- [x] [Tests][testing] passing
- [x] No new [linter issues][linter]

### PR Reviewer Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] [CLIMADA Reviewer Checklist](https://climada-python.readthedocs.io/en/latest/guide/Guide_Reviewer_Checklist.html) passed
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]

[contrib]: https://github.com/CLIMADA-project/climada_python/blob/main/CONTRIBUTING.md
[testing]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html
[linter]: https://climada-python.readthedocs.io/en/stable/guide/Guide_Continuous_Integration_and_Testing.html#3.C.--Static-Code-Analysis

### CODE REVIEW

**Comment by peanutfun** [comment]
This is how it looks like.

Screenshot 2022-12-08 at 12 18 30

**Comment by chahank** [comment]
Great! I would suggest to:

- Re-dd the step by step installation guide
- Add a reference to CLIMADA petals at the top

**Comment by peanutfun** [comment]
Latest version. Note that the "hint" will only appear on ReadTheDocs, not when building the docs on your local machine.

Screenshot 2022-12-09 at 11 11 20

**Comment by peanutfun** [comment]
@emanuel-schmid Could you give this a look? It's now quite a bit but it resolves three issues at once 💪

You will find the preview here: https://climada-python--600.org.readthedocs.build/en/600/

I already incorporated the suggestions by @chahank. This is ready to go!

**Comment by emanuel-schmid** [comment]
🤩

**Pull request merged**
